-- CreateEnum
CREATE TYPE "Role" AS ENUM ('IT_MANAGER', 'PROJECT_MANAGER', 'SOFTWARE_DEVELOPER', 'INTERN', 'QA', 'ANIMATION_2D', 'MNP_2D', 'ANIMATION_3D', 'HR_ADMIN', 'FINANCE_ANALYST');

-- CreateEnum
CREATE TYPE "Department" AS ENUM ('MANAGEMENT', 'DEVELOPMENT', 'QA', 'TEAM_2D', 'TEAM_3D', 'HR', 'IT', 'ANIMATION', 'FINANCE');

-- AlterTable
ALTER TABLE "Employees" ADD COLUMN     "department" "Department" NOT NULL DEFAULT 'IT',
ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'INTERN';
