// TEMPORARY DATA

export let role = "admin";

export const managersData = [
  {
    id: 1,
    managerId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["2D", "2D Animation"],
    projects: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    managerId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["3D", "3D Animation"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    managerId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["Rendering"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    managerId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["Development"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    managerId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["Finance", "HR"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    managerId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["HR"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    managerId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["IT", "Development"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    managerId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["2D", "2D Animation"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    managerId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["3D", "3D Animation"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    managerId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    team: ["IT"],
    projects: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const employeeData = [
  {
    id: 1,
    employeeId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    role: "Software Developer",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Karthik",
    project: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    employeeId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    role: "Software Developer",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Deepak",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    employeeId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    role: "2D Artist",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Karthik",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    employeeId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    role: "Graphic Designer",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Surender Gowl",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    employeeId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    role: "Software Developer",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Surender Gowl",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    employeeId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    role: "Team Lead",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Arjun Reddy",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    employeeId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    role: "Project lead",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Arjun Reddy",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    employeeId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    role: "Software Developer",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Karthik",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    employeeId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    role: "Game Developer",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Arjun Reddy",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    employeeId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    role: "Game Developer",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    manager: "Surender Gowl",
    project: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const hrData = [
  {
    id: 1,
    employeeId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    role: "HR Executive",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    employeeId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    role: "HR Executive",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    employeeId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    role: "HR Manager",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    employeeId: "1234567890",
    name: "Jay French",
    email: "mike@geller.com",
    role: "HR Executive",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    employeeId: "1234567890",
    name: "Jane Smith",
    email: "mike@geller.com",
    role: "HR Intern",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    employeeId: "1234567890",
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    role: "HR Intern",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    employeeId: "1234567890",
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    role: "HR Intern",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    employeeId: "1234567890",
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    role: "HR Manager",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    employeeId: "1234567890",
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    role: "HR Manager",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    employeeId: "1234567890",
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    role: "HR Assistant",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const itData = [
  {
    id: 1,
    employeeId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    role: "IT Executive",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    employeeId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    role: "IT Executive",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    employeeId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    role: "IT Manager",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    employeeId: "1234567890",
    name: "Jay French",
    email: "mike@geller.com",
    role: "IT Executive",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    employeeId: "1234567890",
    name: "Jane Smith",
    email: "mike@geller.com",
    role: "IT Intern",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    employeeId: "1234567890",
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    role: "IT Intern",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    employeeId: "1234567890",
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    role: "IT Intern",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    employeeId: "1234567890",
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    role: "IT Manager",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    employeeId: "1234567890",
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    role: "IT Manager",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    employeeId: "1234567890",
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    role: "IT Assistant",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const teamData = [
  {
    id: 1,
    name: "2D Team",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "3D Team",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "3D Animation",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Development",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "HR",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "House Keeping",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "IT",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Management",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Finance",
    capacity:15, 
    employees: ["Alice Phelps", "Russell Davidson"],
    managers: ["Gertrude Roy", "Rosa Singleton"],
  },
 
];

export const projectsData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja", "beta", "b","karthi","ajmal", "ayaan"],
    manager: "Karthik",
    lead: "Joseph Padilla",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Deepak",
    lead: "Blake Joseph",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Karthik",
    lead: "Tom Bennett",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Surender Gowl",
    lead: "Aaron Collins",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Surender Gowl",
    lead: "Iva Frank",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Surender Gowl",
    lead: "Leila Santos",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Surender Gowl",
    lead: "Carrie Walton",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Surender Gowl",
    lead: "Christopher Butler",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Arjun Reddy",
    lead: "Marc Miller",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    manager: "Arjun Reddy",
    lead: "Ophelia Marsh",
    client: "Mayme Keller",
    deadline: "2025-04-01",
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    title: "Picnic",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    title: "Beach Trip",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    title: "Cricket Tournament",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    title: "Music Concert",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    title: "Magician Show",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    title: "Team Lunch",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    title: "Team Outing",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    title: "Art Exhibition",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    title: "Sports Tournament",
    capacity: 20,
    employees:["Gertrude Roy", "Rosa Singleton", "alpja"],
    organizers: ["Alice Phelps", "Russell Davidson"],
    days: 1,
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    address: "123 Main St, Anytown, USA",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About Townhall",
    capacity: 116,
    sendBy:"Ankit",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    location: "conference hall",
    message:"Empower your people to go above and beyond with a flexible platform designed to match the needs of your team",
  },
  {
    id: 2,
    title: "About ShiftChanges",
    capacity: 36,
    sendBy:"Ankit",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    location: "conference hall",
    message:"Empower your people to go above and beyond with a flexible platform designed to match the needs of your team",
  },
  {
    id: 3,
    title: "Team Update",
    capacity: 16,
    sendBy:"Ankit",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    location: "conference hall",
    message:"Empower your people to go above and beyond with a flexible platform designed to match the needs of your team",
  },
  {
    id: 4,
    title: "Project update",
    capacity: 76,
    sendBy:"Ankit",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    location: "conference hall",
    message:"Empower your people to go above and beyond with a flexible platform designed to match the needs of your team",
  },
  {
    id: 5,
    title: "festival celebrations",
    capacity: 116,
    sendBy:"Ankit",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    location: "conference hall",
    message:"Empower your people to go above and beyond with a flexible platform designed to match the needs of your team",
  },
  {
    id: 6,
    title: "Townhall",
    capacity: 116,
    sendBy:"Ankit",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    location: "conference hall",
    message:"Empower your people to go above and beyond with a flexible platform designed to match the needs of your team",
  },
  {
    id: 7,
    title: "Project Update",
    capacity: 16,
    sendBy:"Ankit",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    location: "conference hall",
    message:"Empower your people to go above and beyond with a flexible platform designed to match the needs of your team",
  },
  {
    id: 8,
    title: "Project update",
    capacity: 16,
    sendBy:"Ankit",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
    location: "conference hall",
    message:"Empower your people to go above and beyond with a flexible platform designed to match the needs of your team",
  },
  
];

export const leaveData = [
  {
    id: 1,
    leaveType: "Causual Leave",
    days: 2,
    startDate: "2025-01-01",
    endDate: "2025-01-02",
    reason: "Family Function ",
    manager:"karthik",
    status:"Approved",
    lop: "no"
  },
  {
    id: 2,
    leaveType: "Causual Leave",
    days: 2,
    startDate: "2025-01-01",
    endDate: "2025-01-02",
    reason: "Family Function ",
    manager:"karthik",
    status:"Approved",
    lop: "no"
  },
  {
    id: 3,
    leaveType: "Causual Leave",
    days: 2,
    startDate: "2025-01-01",
    endDate: "2025-01-02",
    reason: "Family Function ",
    manager:"karthik",
    status:"Approved",
    lop: "no"
  },
  {
    id: 4,
    leaveType: "Causual Leave",
    days: 2,
    startDate: "2025-01-01",
    endDate: "2025-01-02",
    reason: "Family Function ",
    manager:"karthik",
    status:"Approved",
    lop: "no"
  },
  {
    id: 5,
    leaveType: "Causual Leave",
    days: 2,
    startDate: "2025-01-01",
    endDate: "2025-01-02",
    reason: "Family Function ",
    manager:"karthik",
    status:"Approved",
    lop: "no"
  },
  {
    id: 6,
    leaveType: "Causual Leave",
    days: 2,
    startDate: "2025-01-01",
    endDate: "2025-01-02",
    reason: "Family Function ",
    manager:"karthik",
    status:"Approved",
    lop: "no"
  },
  {
    id: 7,
    leaveType: "Causual Leave",
    days: 2,
    startDate: "2025-01-01",
    endDate: "2025-01-02",
    reason: "Family Function ",
    manager:"karthik",
    status:"Approved",
    lop: "no"
  },
  {
    id: 8,
    leaveType: "Causual Leave",
    days: 2,
    startDate: "2025-01-01",
    endDate: "2025-01-02",
    reason: "Family Function ",
    manager:"karthik",
    status:"Approved",
    lop: "no"
  },
  
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Meeting",
    allDay: false,
    start: new Date(2025, 3, 7, 10, 0),
    end: new Date(2025, 3, 7, 10, 30),
  },
  {
    title: "Team Meeting",
    allDay: false,
    start: new Date(2025, 3, 8, 12, 0),
    end: new Date(2025, 3, 8, 12, 30),
  },
  {
    title: "project Meeting",
    allDay: false,
    start: new Date(2025, 3, 7, 15, 30),
    end: new Date(2025, 3, 7, 15, 45),
  },
  {
    title: "Project Update meeting",
    allDay: false,
    start: new Date(2025, 3,10,  11, 0),
    end: new Date(2025, 3,10, 11, 45),
  },
  {
    title: "Project Changes Meeting",
    allDay: false,
    start: new Date(2025, 3, 9, 13, 0),
    end: new Date(2025, 3, 9, 13, 45),
  },
  {
    title: "Project Testing Meeting",
    allDay: false,
    start: new Date(2025, 3, 11, 14, 0),
    end: new Date(2025, 3, 11, 14, 45),
  },
  {
    title: "Project Submission Meeting",
    allDay: false,
    start: new Date(2025, 3, 10, 9, 30),
    end: new Date(2025, 3, 10, 9, 45),
  },
  {
    title: "Project Modifications",
    allDay: false,
    start: new Date(2025, 3, 9, 10, 0),
    end: new Date(2025, 3, 9, 10, 45),
  },
  {
    title: "Project updates",
    allDay: false,
    start: new Date(2025, 3, 8, 11, 0),
    end: new Date(2025, 3, 8, 11, 45),
  },
  {
    title: "Client followup",
    allDay: false,
    start: new Date(2025, 3, 10, 15, 0),
    end: new Date(2025, 3, 10, 15, 45),
  },
  {
    title: "client Meeting",
    allDay: false,
    start: new Date(2025, 3, 11, 17, 0),
    end: new Date(2025, 3, 11, 17, 30),
  },
];